### ISSUE TITLE
Modify the example1

### ISSUE THREAD

**Issue by EthanDBer** [AntonioLonga/PytorchGeometricTutorial#2]
https://github.com/AntonioLonga/PytorchGeometricTutorial/blob/main/Tutorial1/Tutorial1.ipynb

I think this example could be modified for the better. In fact, the nums_layer = 1 parameter should be defined in Net, and a layer of GNNStack should be defined according to this parameter in the forward method. This would solve the problem raised by YouTube video 43:29.

**Comment by AntonioLonga** [comment]
Hi EthanDBer,

Thanks for your comment! I totally agree with you.

Thanks again

**Comment by EthanDBer** [comment]
```python
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        self.conv = SAGEConv(dataset.num_features,
                             dataset.num_classes,
                             aggr="max") # max, mean, add ...)
        self.num_layers = 1
    def forward(self):
        for i in range(self.num_layers):
          x = self.conv(data.x, data.edge_index)
        return F.log_softmax(x, dim=1)
```
