### ISSUE TITLE
Adding Colab support for the tutorials

### ISSUE THREAD

**Issue by Godofnothing** [AntonioLonga/PytorchGeometricTutorial#3]
Thanks for your effort and great work! 

I think, In order to make the tutorials more convenient for a wide audience it would be helpful to add a `colab` version of the notebooks with the special button, that redirects to the http://colab.research.google.com/. 

All tutorials can be run in `colab` via adding the notebook from GitHub and adding the cell with the installation of the `pytorch-geometric` and all dependencies. But the version with native support would make it more convenient.

**Comment by AntonioLonga** [comment]
Thanks for the suggestion, we added the colab version.
