### ISSUE TITLE
Error for running "from torch_geometric.nn import Node2Vec"

### ISSUE THREAD

**Issue by ayreen2** [AntonioLonga/PytorchGeometricTutorial#5]
while running from torch_geometric.nn import Node2Vec in google colab an error occur
OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cpu.so: undefined symbol: _ZNK2at6Tensor5zero_Ev

what should I do?

**Comment by AntonioLonga** [comment]
hi,
you have to update pyg, then it should work.
