### ISSUE TITLE
Tutorial 3 code

### ISSUE THREAD

**Issue by vandana-rajan** [AntonioLonga/PytorchGeometricTutorial#7]
Hi,

Thanks for this great tutorials and videos. Really nice work.

I was wondering about the GATLayer class in the code of tutorial 3. Once the class is made, it is no longer used after the 'Use it' heading in the notebook. Instead, the GATConv from torch geometric is used directly. Then why was the GATLayer class made?

Thanks,
VR

**Comment by AntonioLonga** [comment]
Hi,

Thanks, sorry for the late reply.

GATConv is developed in the library, while LAF has been developed by G.Pellegrini (the guy presenting).
