### ISSUE TITLE
Tutorial 3 unable to load laf_model

### ISSUE THREAD

**Issue by chensyCN** [AntonioLonga/PytorchGeometricTutorial#8]
While running tut3 on colab, the following error occurs, details are as shown below:
![](https://raw.githubusercontent.com/chensyCN/PicBed/main/%E6%88%AA%E5%B1%8F2022-02-28%20%E4%B8%8B%E5%8D%885.11.35.png)

**Comment by AntonioLonga** [comment]
Hi,

sorry for the late replay. 

I've fixed the problem

best,
Antonio
